fn main() {
    // Phase 19 - `launch_application` is the app's first ever frontend-
    // invokable command (see src/os_launcher.rs); Tauri 2's ACL denies
    // every command by default, even ones defined in the app itself, so it
    // needs an explicit permission. `.commands([...])` autogenerates the
    // standard `allow-launch-application`/`deny-launch-application`
    // permission pair (written to permissions/autogenerated/) that
    // capabilities/default.json references.
    let attributes = tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&["launch_application"]));
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
