// The Companies Database stores company facts only - researched once, not
// re-entered per role. Application status, fit rating, and everything else
// that varies per job opening lives on the Vacancy entity instead (see
// _lib/types/vacancy.ts), since a single company can have many open roles
// each at a different stage.

export type YesNoUnknown = "Unknown" | "Yes" | "No";

export const YES_NO_UNKNOWN_OPTIONS: ReadonlyArray<YesNoUnknown> = ["Unknown", "Yes", "No"];

export type CompanyEntry = Readonly<{
  id: string;

  // Basic Information
  name: string;
  country: string;
  city: string;
  website: string;
  industry: string;
  companySize: string;

  // Career Opportunities
  careersPageUrl: string;
  linkedinUrl: string;
  graduateProgramsAvailable: YesNoUnknown;
  visaSponsorship: YesNoUnknown;
  englishFriendlyEnvironment: YesNoUnknown;

  // Notes
  notes: string;
}>;

export function createCompanyId() {
  return `company-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// Used by both manual "+ Add Company" and bulk import - only the name is
// known up front, everything else stays empty/unknown until researched.
export function createCompanyEntry(name: string): CompanyEntry {
  return {
    id: createCompanyId(),
    name,
    country: "",
    city: "",
    website: "",
    industry: "",
    companySize: "",
    careersPageUrl: "",
    linkedinUrl: "",
    graduateProgramsAvailable: "Unknown",
    visaSponsorship: "Unknown",
    englishFriendlyEnvironment: "Unknown",
    notes: "",
  };
}

type CompanySeed = {
  name: string;
  country: string;
  industry: string;
  companySize: string;
  careersPageUrl: string;
  researchNotes: string;
};

// Sourced from a personal target-company research spreadsheet (market cap /
// revenue / earnings screen of large employers, cross-referenced with open
// graduate-engineer roles). Financials and headcount live in researchNotes
// as reference context only - Fit Score, Skill Match, and Priority are
// still set by hand per the comment above.
const COMPANY_SEED_DATA: ReadonlyArray<CompanySeed> = [
  { name: "Saudi Aramco", country: "Saudi Arabia", industry: "Oil and Gas", companySize: "75,000", careersPageUrl: "", researchNotes: "Market Cap: €1,501B | Revenue 2024: €461.82B | Earnings 2024: €182.71B" },
  { name: "ASML", country: "Netherlands", industry: "Semiconductor Equipment", companySize: "44,000", careersPageUrl: "", researchNotes: "Market Cap: €604.01B | Revenue 2024: €28.26B | Earnings 2024: €9.02B" },
  { name: "ExxonMobil", country: "United States", industry: "Oil and Gas", companySize: "58,000", careersPageUrl: "https://jobs.exxonmobil.com/job/Machelen-Research-Lab-Technician-1831/1381663000/", researchNotes: "Market Cap: €551.16B | Revenue 2024: €326.01B | Earnings 2024: €42.81B" },
  { name: "Chevron", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €333.53B" },
  { name: "Roche", country: "Switzerland", industry: "Pharma/Healthcare", companySize: "", careersPageUrl: "https://careers.roche.com/global/en/operations-rotational-development-program", researchNotes: "Market Cap: €285.50B\n\nOther open roles:\n- https://ch.indeed.com/viewjob?jk=4445b83598550e95&from=shareddesktop_copy" },
  { name: "AstraZeneca", country: "United Kingdom", industry: "Pharma/Healthcare", companySize: "", careersPageUrl: "https://careers.astrazeneca.com/engineering-graduate", researchNotes: "Market Cap: €261.44B\n\nOther open roles:\n- https://careers.astrazeneca.com/operations-global-graduate-associates-programme" },
  { name: "Novartis", country: "Switzerland", industry: "Pharma/Healthcare", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €254.25B" },
  { name: "GE Vernova", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "https://careers.gevernova.com/edison-engineering-development-program", researchNotes: "Market Cap: €254.09B\n\nOther open roles:\n- https://careers.gevernova.com/operations-management-development-program\n- https://gevernova.dejobs.org/remote-ita/field-engineering-program-technical-field-advisor-hd-gas-turbine/3663AC45508745668E9BCF562B1BB745/job/?vs=8010" },
  { name: "Siemens", country: "Germany", industry: "Industrial/Engineering Conglomerate", companySize: "", careersPageUrl: "https://jobs.siemens.com/en_US/externaljobs/JobDetail/514648", researchNotes: "Market Cap: €223.21B\n\nOther open roles:\n- https://jobs.siemens.com/en_US/externaljobs/JobDetail/511702\n- https://it.whatjobs.com/engineering-graduate-rotational-program-jobs/page-23?id=219734426" },
  { name: "Nestle", country: "Switzerland", industry: "Food & Beverage", companySize: "", careersPageUrl: "https://jobdetails.nestle.com/job/Konolfingen-Engineering-Specialist/1367415633/?feedId=256801&utm_source=NestleCareers", researchNotes: "Market Cap: €221.63B" },
  { name: "Shell", country: "United Kingdom", industry: "Energy/Chemicals", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4432188943&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €221.11B" },
  { name: "Linde", country: "United Kingdom", industry: "Industrial Gases/Chemicals", companySize: "", careersPageUrl: "https://linde.csod.com/ux/ats/careersite/20/home/requisition/31553?c=linde", researchNotes: "Market Cap: €218.94B\n\nDeadline: 30 July" },
  { name: "L'Oreal", country: "France", industry: "Consumer Goods (Cosmetics)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €212.97B" },
  { name: "TotalEnergies", country: "France", industry: "Energy/Chemicals", companySize: "", careersPageUrl: "https://jobs.totalenergies.com/en_US/careers/JobDetail/METHODS-PROCESS-INDUSTRIALIZATION-ENGENEER/82715", researchNotes: "Market Cap: €185.46B\n\nOther open roles:\n- https://jobs.totalenergies.com/en_US/careers/JobDetail/AUTOMATION-TECHNICIAN/82535\n- https://jobs.totalenergies.com/en_US/careers/JobDetail/Ing-nieur-R-servoir-Digital-D-butant-H-F/76612\n- https://jobs.totalenergies.com/en_US/careers/JobDetail/VIE-Ing-nieur-R-servoir-H-F-Norv-ge/81580" },
  { name: "Novo Nordisk", country: "Denmark", industry: "Pharma/Biomanufacturing", companySize: "", careersPageUrl: "https://www.novonordisk.com/careers/early-career-programmes/graduate/application-process.html", researchNotes: "Market Cap: €179.46B" },
  { name: "Schneider Electric", country: "France", industry: "Industrial/Engineering Automation", companySize: "", careersPageUrl: "https://careers.se.com/jobs/112736?lang=en-us&previousLocale=en-US", researchNotes: "Market Cap: €170.57B\n\nOther open roles:\n- https://careers.se.com/jobs/117599?lang=en-us&previousLocale=en-US\n- https://careers.se.com/jobs/121378?lang=en-us&previousLocale=en-US\n- https://careers.se.com/jobs/108257?lang=en-us&previousLocale=en-US\n- https://careers.se.com/jobs/122523?lang=en-us&previousLocale=en-US\n- https://careers.se.com/jobs/121513?lang=en-us&previousLocale=en-US" },
  { name: "Nextera Energy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €160.73B" },
  { name: "Rio Tinto", country: "United Kingdom", industry: "Mining", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €160.11B" },
  { name: "ABB", country: "Switzerland", industry: "Industrial/Electrical Equipment", companySize: "", careersPageUrl: "https://careers.abb/global/en/job/JR00041011/Global-Project-Manager-Process-Automation", researchNotes: "Market Cap: €160.04B\n\nOther open roles:\n- https://careers.abb/global/en/job/JR00037475/R-D-Testing-Lab-Specialist\n- https://careers.abb/global/en/job/JR00039636/Sustainability-specialist-internship\n- https://careers.abb/global/en/job/JR00032251/ABB-Student-Program-diplomov%C3%A9-bakal%C3%A1%C5%99sk%C3%A9-pr%C3%A1ce-a-st%C3%A1%C5%BEe-praxe\n- https://careers.abb/global/en/job/JR00038491/Junior-Test-Engineer\n- https://careers.abb/global/en/job/JR00042579/PV-Control-Engineer\n- https://careers.abb/global/en/job/JR00037776/Production-Development-Engineer" },
  { name: "Eaton", country: "Ireland", industry: "Industrial/Electrical Equipment", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4395844997&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €150.51B" },
  { name: "Siemens Energy", country: "Germany", industry: "Energy Engineering", companySize: "", careersPageUrl: "https://www.siemens-energy.com/global/en/home/careers/graduate-program.html", researchNotes: "Market Cap: €145.31B" },
  { name: "Iberdrola", country: "Spain", industry: "Utilities (Electricity)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €142.18B" },
  { name: "ConocoPhillips", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €125.47B" },
  { name: "Infineon", country: "Germany", industry: "Semiconductors", companySize: "", careersPageUrl: "https://jobs.infineon.com/careers/job/563808971615620?hl=en", researchNotes: "Market Cap: €118.88B\n\nOther open roles:\n- https://jobs.infineon.com/careers?hl=en&start=40&pid=563808971708891&sort_by=timestamp&filter_join_as=graduate+%28incl.+graduate+programs%29" },
  { name: "Hitachi", country: "Japan", industry: "Engineering", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4427917211&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €115.89B\n\nOther open roles:\n- https://www.hitachienergy.com/careers/open-jobs/details/JID3-183224\n- https://www.hitachienergy.com/careers/open-jobs/details/JID3-206304\n- https://www.hitachienergy.com/careers/open-jobs/details/JID3-204846\n- https://ch.indeed.com/viewjob?jk=e718165e4048eca2&from=shareddesktop_copy\n- https://ch.indeed.com/viewjob?jk=44a78f85e5807432&from=shareddesktop_copy\n- https://ch.indeed.com/viewjob?jk=3f1b390c407e002a&from=shareddesktop_copy\n- https://ch.indeed.com/viewjob?jk=d31e321fb6d362a5&from=shareddesktop_copy" },
  { name: "Air Liquide", country: "France", industry: "Industrial Gases", companySize: "", careersPageUrl: "https://airliquidehr.wd3.myworkdayjobs.com/ru-RU/AirLiquideExternalCareer/job/Italy-Milano/Junior-Project-Manager---Allex-Graduate-Program_R10094467?q=allex", researchNotes: "Market Cap: €112.77B\n\nOther open roles:\n- https://airliquidehr.wd3.myworkdayjobs.com/ru-RU/AirLiquideExternalCareer/job/Belgium-Brussel/Junior-Operations-Engineer_R10091748-1?q=allex\n- https://airliquidehr.wd3.myworkdayjobs.com/ru-RU/AirLiquideExternalCareer/job/Poland-Krakw/Junior-Project-Engineer--ALLEX-Graduate-Program-_R10095855-1?q=allex&locationCountry= bdc96e498e412&locationCountry=9696868b09c64d52a62ee13b052383cc&locationCountry=8cd04a563fd94da7b06857a79faaf815&locationCountry=49ab063f422741e2aef271de00efeac8&locationCountry=29247e57dbaf46fb855b224e03170bc7&locationCountry=d004c0d1a6c84511ab048669fcdf9fd7&locationCountry=dcc5b7608d8644b3a93716604e78e995&locationCountry=a04ea128f43a42e59b1e6a19e8f0b374" },
  { name: "Unilever", country: "United Kingdom", industry: "Consumer Goods", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €111.17B" },
  { name: "Parker-Hannifin", country: "United States", industry: "", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €107.37B | Revenue 2024: €19.13B | Earnings 2024: €3.46B" },
  { name: "BP", country: "United Kingdom", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €103.59B" },
  { name: "Enel", country: "Italy", industry: "Utilities (Electricity)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €102.11B" },
  { name: "Sanofi", country: "France", industry: "Pharma", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €98.37B" },
  { name: "Trane Technologies", country: "Ireland", industry: "Industrial/HVAC Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €94.92B" },
  { name: "GSK", country: "United Kingdom", industry: "Pharma/Healthcare", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4423650166&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €94.54B\n\nAlso hiring in: Germany\n\nOther open roles:\n- https://www.joinrs.com/en/jobs/2625126" },
  { name: "Southern Company", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €92.73B" },
  { name: "Equinor", country: "Norway", industry: "Energy", companySize: "", careersPageUrl: "https://www.equinor.com/careers/graduates", researchNotes: "Market Cap: €87.53B\n\nOther open roles:\n- https://www.equinor.com/careers/petroleum-engineering-and-geosciences" },
  { name: "Duke Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €86.03B" },
  { name: "Quanta Services", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €84.07B" },
  { name: "Constellation Energy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €82.07B" },
  { name: "Valero Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €81.93B" },
  { name: "Marathon Petroleum", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €81.82B" },
  { name: "Glencore", country: "Switzerland", industry: "Mining/Commodities", companySize: "", careersPageUrl: "https://job-boards.eu.greenhouse.io/glencoreuk/jobs/4912086101?gh_src=pilei1o2teu", researchNotes: "Market Cap: €80.11B\n\nOther open roles:\n- https://www.glencore.com/en/careers/jobs/R200001654\n- https://www.glencore.com/en/careers/jobs/R200001645" },
  { name: "Williams Companies", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €78.63B" },
  { name: "Atlas Copco", country: "Sweden", industry: "Industrial Equipment/Engineering", companySize: "", careersPageUrl: "https://www.atlascopco.com/en-uk/jobs/job-overview/job-detail/technology-engineer/163283-atlascopco", researchNotes: "Market Cap: €77.76B\n\nOther open roles:\n- https://www.atlascopco.com/en-uk/jobs/job-overview/job-detail/project-engineer-energy-conversion/168664-atlascopco" },
  { name: "Phillips 66", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €74.59B" },
  { name: "ENI", country: "Italy", industry: "Energy", companySize: "", careersPageUrl: "https://jobs.eni.com/en/sites/CX_1004/job/33587/?utm_medium=jobshare&utm_source=External+Job+Share", researchNotes: "Market Cap: €73.91B" },
  { name: "Enterprise Products", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €73.12B" },
  { name: "ENGIE", country: "France", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €72.69B" },
  { name: "Sherwin-Williams", country: "United States", industry: "Paint and Coatings", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €69.58B | Revenue 2024: €22.20B | Earnings 2024: €3.02B" },
  { name: "Emerson", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4441444921&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €68.36B | Revenue 2024: €16.87B | Earnings 2024: €2.61B\n\nOther open roles:\n- https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/26007418/?lastSelectedFacet=LOCATIONS&selectedLocationsFacet=300000000228642%253B300000024887636%253B300000024887638%253B300000024902059%253B300000000228696%253B300000000229008%253B300000027787843%253B300000031320484%253B300000000228801%253B300000024887644&selectedTitlesFacet=DEVELOPMENT+ENGINEERING%253BMANUFACTURING%253BENGINEERING+SERVICES%253BMATERIALS+AND+PROCUREMENT%253BTECHNICIAN%253BMANUFACTURING+ENGINEERING" },
  { name: "EOG Resources", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €66.96B" },
  { name: "NXP Semiconductors", country: "Netherlands", industry: "Semiconductors", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €66.72B" },
  { name: "CRH", country: "Ireland", industry: "Building Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €65.94B" },
  { name: "Honeywell", country: "United States", industry: "", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €65.82B | Revenue 2024: €37B | Earnings 2024: €7.24B" },
  { name: "Merck KGaA", country: "Germany", industry: "Pharma/Specialty Chemicals", companySize: "", careersPageUrl: "https://careers.merckgroup.com/global/en/life-science-graduate-programs#902", researchNotes: "Market Cap: €65.24B" },
  { name: "Kinder Morgan", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €63.14B" },
  { name: "Energy Transfer LP", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €61.07B" },
  { name: "Schlumberger", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "https://careers.slb.com/jobdescription.aspx?id=FieldEng&location=%27United%20KingdomMulti-Location%27", researchNotes: "Market Cap: €61.05B\n\nOther open roles:\n- https://careers.slb.com/job-listing#sortCriteria=%40title%20ascending&f-category-job=Operations%20(Engineers%2C%20Geoscience%2C%20Specialists%2C%20Operators),Engineering%20%26% 20Prod%22" },
  { name: "STMicroelectronics", country: "Switzerland", industry: "Semiconductors", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €60.10B" },
  { name: "Air Products and Chemical", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "https://airproducts.wd5.myworkdayjobs.com/en-US/AP0001/details/Plant-Project-Engineer--Large-Projects-Europe_JR-2026-21178?locationCountry=29247e57dbaf46fb855b224e03170bc7= 99&locationCountry=a04ea128f43a42e59b1e6a19e8f0b374", researchNotes: "Market Cap: €57.84B\n\nOther open roles:\n- https://airproducts.wd5.myworkdayjobs.com/en-US/AP0001/details/Technical-Co-Ordinator_JR-2026-19480?locationCountry=29247e57dbaf46fb855b224e03170bc7&locationCountry=bd34c524a6a04ae6915f5d96fa086199&locationCountry=2e8c5034deb045d49315417c347472ca&locationCountry=131d5ac7e3ee4d7b962bdc96e498e412&locationCountry=d07f8ca8625e4345b98a91d0558b872a&locationCountry=9696868b09c64d52a62ee13b052383cc&locationCountry=04a05835925f45b3a59406a2a6b72c8a&locationCountry=9db257f5937e4421b2fac64eec6832f8&locationCountry=dcc5b7608d8644b3a93716604e78e995&locationCountry=54c5b6971ffb4bf0b116fe7651ec789a&locationCountry=fc078443155c4ad294201ecf5a61a499&locationCountry=a04ea128f43a42e59b1e6a19e8f0b374" },
  { name: "Bloom Energy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €56.41B" },
  { name: "Anglo American", country: "United Kingdom", industry: "Mining", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €54.12B" },
  { name: "Dominion Energy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €53.84B" },
  { name: "UCB", country: "Belgium", industry: "Pharma", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €53.31B" },
  { name: "Targa Resources", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €52.71B" },
  { name: "TE Connectivity", country: "Switzerland", industry: "Electronics/Connectivity", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €52.49B" },
  { name: "Sempra", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €51.90B" },
  { name: "Antofagasta", country: "United Kingdom", industry: "Mining", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €51.06B" },
  { name: "Corteva", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €50.96B" },
  { name: "E.ON", country: "Germany", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €50.75B" },
  { name: "Oneok", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €50.71B" },
  { name: "ArcelorMittal", country: "Luxembourg", industry: "Steel/Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €50.45B" },
  { name: "MPLX", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €50.24B" },
  { name: "Diamondback Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €49.26B" },
  { name: "Occidental Petroleum", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €49.25B" },
  { name: "Baker Hughes", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "https://careers.bakerhughes.com/global/en/job/R160038/Field-Engineer-I-PPS-FLD-G", researchNotes: "Market Cap: €49.02B\n\nOther open roles:\n- https://careers.bakerhughes.com/global/en/search-results?from=120&s=1\n- https://it.whatjobs.com/engineering-graduate-rotational-program-jobs/page-19?id=210783073" },
  { name: "Cheniere Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €48.23B" },
  { name: "BASF", country: "Germany", industry: "Chemicals", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4433710333&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €48.17B" },
  { name: "Vistra", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €47.97B" },
  { name: "ASM International", country: "Netherlands", industry: "Semiconductor Equipment", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €47.93B" },
  { name: "Sandvik", country: "Sweden", industry: "Industrial Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €47.36B" },
  { name: "Prysmian Group", country: "Italy", industry: "Cables/Materials Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €47.34B" },
  { name: "Entergy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €45.89B" },
  { name: "Rockwell Automation", country: "United States", industry: "", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €45.66B | Revenue 2024: €7.78B | Earnings 2024: €0.92B" },
  { name: "Devon Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €44.58B" },
  { name: "Holcim Group", country: "Switzerland", industry: "Building Materials", companySize: "", careersPageUrl: "https://ch.indeed.com/viewjob?jk=af8ebacc563d817f&from=shareddesktop_copy", researchNotes: "Market Cap: €43.37B" },
  { name: "Xcel Energy", country: "United States", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €43.07B" },
  { name: "ORLEN", country: "Poland", industry: "Energy", companySize: "", careersPageUrl: "https://kariera.orlenunipetrol.cz/en-us/graduate-programme", researchNotes: "Market Cap: €43.02B" },
  { name: "Galderma Group", country: "Switzerland", industry: "Pharma/Dermatology", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €42.88B" },
  { name: "RWE", country: "Germany", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4427027176&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €42.83B" },
  { name: "Endesa", country: "Spain", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €42.16B" },
  { name: "Hess", country: "United States", industry: "Energy, Oil and gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €40.35B | Revenue 2024: €12.39B | Earnings 2024: €4.17B" },
  { name: "Compagnie de Saint-Gobain", country: "France", industry: "Building Materials/Industrial", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €40.31B" },
  { name: "Bayer", country: "Germany", industry: "Pharma/Chemicals", companySize: "", careersPageUrl: "https://bayer.eightfold.ai/careers?pid=562949974736435&job%20type=student&job%20type=job%20starter&job%", researchNotes: "Market Cap: €37.57B" },
  { name: "Sabic", country: "Saudi Arabia", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €37.37B" },
  { name: "Lonza", country: "Switzerland", industry: "Pharma/Biotech Manufacturing", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €37.27B" },
  { name: "Daikin", country: "Japan", industry: "Manufacturing", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €36.24B" },
  { name: "SSE", country: "United Kingdom", industry: "Utilities (Electricity)", companySize: "", careersPageUrl: "https://careers.sse.com/graduate-engineering-programme", researchNotes: "Market Cap: €35.72B" },
  { name: "Samsung C&T Corporation", country: "South Korea", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €34.32B" },
  { name: "PG&E Corporation", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €33.76B" },
  { name: "Epiroc", country: "Sweden", industry: "Industrial Equipment (Mining)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €32.31B" },
  { name: "Givaudan", country: "Switzerland", industry: "Specialty Chemicals (Flavors/Fragrances)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €31.46B" },
  { name: "Sandoz Group", country: "Switzerland", industry: "Pharma (Generics)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €31B" },
  { name: "Grupo ACS", country: "Spain", industry: "Construction/Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €30.72B" },
  { name: "Venture Global", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €30.61B" },
  { name: "Orsted", country: "Denmark", industry: "Energy (Offshore Wind)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €30.23B\n\nAlso hiring in: Norway" },
  { name: "CEZ Group", country: "Czech Republic", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €29.76B" },
  { name: "Henkel", country: "Germany", industry: "Chemicals/Consumer Goods", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €29.14B" },
  { name: "Tenaris", country: "Luxembourg", industry: "Steel/Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €28.72B" },
  { name: "Naturgy", country: "Spain", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €28.60B" },
  { name: "EQT Corporation", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €27.30B" },
  { name: "Veolia", country: "France", industry: "Environmental Services/Engineering", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4442077329&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €27.25B" },
  { name: "Halliburton", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €27.05B" },
  { name: "Repsol", country: "Spain", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €27B" },
  { name: "Ingersoll Rand", country: "Ireland", industry: "Industrial Equipment", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €26.18B" },
  { name: "Sika", country: "Switzerland", industry: "Specialty Chemicals/Construction Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €25.49B" },
  { name: "TechnipFMC", country: "United Kingdom", industry: "Energy Engineering", companySize: "", careersPageUrl: "https://careers.technipfmc.com/job/Hyderabad-Associate-Quality-Analyst/1409006900/", researchNotes: "Market Cap: €25.08B" },
  { name: "Amrize", country: "Switzerland", industry: "Building Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €25.07B" },
  { name: "Kone", country: "Finland", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.50B" },
  { name: "EnBW Energie", country: "Germany", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.44B" },
  { name: "Novonesis", country: "Denmark", industry: "Biotech/Enzymes", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.41B" },
  { name: "Michelin", country: "France", industry: "Materials (Tires)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.40B" },
  { name: "MasTec", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.33B" },
  { name: "Vestas Wind Systems", country: "Denmark", industry: "Energy (Wind Engineering)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.31B" },
  { name: "Coterra Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €24.30B" },
  { name: "Neste", country: "Finland", industry: "Energy/Renewables", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4412128697&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €23.46B\n\nOther open roles:\n- https://jobs.neste.com/job/Rotterdam-Process-Engineer/1409993300/\n- https://jobs.neste.com/job/Rotterdam-Junior-Process-Control-Engineer/1389335800/" },
  { name: "BE Semiconductor (Besi)", country: "Netherlands", industry: "Semiconductor Equipment", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €23.43B" },
  { name: "Norsk Hydro", country: "Norway", industry: "Materials (Aluminum)/Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €23.18B" },
  { name: "PPG Industries", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €22.60B" },
  { name: "Snam", country: "Italy", industry: "Gas Infrastructure Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €22.54B" },
  { name: "Wartsila", country: "Finland", industry: "Marine/Energy Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €22.38B" },
  { name: "OMV", country: "Austria", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €22.36B" },
  { name: "Aker BP", country: "Norway", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €22B" },
  { name: "Alfa Laval", country: "Sweden", industry: "Process Equipment Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €21.79B" },
  { name: "Verbund AG", country: "Austria", industry: "Utilities (Hydropower)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €21.76B" },
  { name: "Expand Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €21.67B" },
  { name: "VAT Group", country: "Switzerland", industry: "Semiconductor Equipment", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €21.26B" },
  { name: "Uniper", country: "Germany", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €21.09B" },
  { name: "BioNTech", country: "Germany", industry: "Biotech/Pharma Manufacturing", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €20.62B" },
  { name: "Fortum", country: "Finland", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €20.22B" },
  { name: "Smurfit Westrock", country: "Ireland", industry: "Packaging Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €20.04B" },
  { name: "EDP Group", country: "Portugal", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €19.33B" },
  { name: "Constellation Oil Services Holding", country: "Luxembourg", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €19.30B" },
  { name: "Dow", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €19.24B" },
  { name: "SGS", country: "Switzerland", industry: "Testing/Inspection Services", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €19.07B" },
  { name: "Bouygues", country: "France", industry: "Construction", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €18.60B" },
  { name: "DSM-Firmenich", country: "Switzerland", industry: "Specialty Chemicals", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4423171545&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €17.81B" },
  { name: "Ems-Chemie", country: "Switzerland", industry: "Specialty Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €17.50B" },
  { name: "KGHM Polska Miedz", country: "Poland", industry: "Mining/Metallurgy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €17.36B" },
  { name: "LyondellBasell", country: "Netherlands", industry: "Chemicals", companySize: "", careersPageUrl: "https://www.lyondellbasell.com/en/careers/students-graduates/europe/emerging-leaders-program/", researchNotes: "Market Cap: €17.31B" },
  { name: "Essity", country: "Sweden", industry: "Consumer Goods (Hygiene)", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/essity/rst-process-engineer-prudhoe-2026-aiqs?search_id=66bac72089eecbd8a0c512f305119a04&search_position=3", researchNotes: "Market Cap: €17.07B\n\nAlso hiring in: United Kingdom" },
  { name: "Western Midstream", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €16.87B" },
  { name: "Dupont De Nemours", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "https://careers.dupont.com/us/en/job/249549W/Process-Engineer-Tyvek%C2%AE-m-f-d", researchNotes: "Market Cap: €16.42B\n\nOther open roles:\n- https://careers.dupont.com/us/en/job/249350W/R-D-Scientist-Battery-Thermal-Materials-Contractor-position\n- https://careers.dupont.com/us/en/job/249360W/Polymer-Processing-Engineer-Lab-Healthcare-Solutions-m-f-d\n- https://careers.dupont.com/us/en/job/249384W/Field-Service-Technician-II" },
  { name: "Galp Energia", country: "Portugal", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €16.39B" },
  { name: "Amcor", country: "Switzerland", industry: "Packaging", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €15.97B" },
  { name: "EDP Renovaveis", country: "Spain", industry: "Energy (Renewables)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €15.86B" },
  { name: "Permian Resources", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €15.84B" },
  { name: "Kingspan Group", country: "Ireland", industry: "Building Materials Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €15.81B" },
  { name: "Plains All American Pipeline", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €15.02B" },
  { name: "Api Group", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.84B" },
  { name: "Ovintiv", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.62B" },
  { name: "Ipsen", country: "France", industry: "Pharma", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.61B" },
  { name: "HF Sinclair", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.48B" },
  { name: "Acciona", country: "Spain", industry: "Construction/Renewable Energy Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.32B" },
  { name: "Boliden", country: "Sweden", industry: "Mining/Metallurgy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.19B" },
  { name: "Viper Energy", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.15B" },
  { name: "UPM-Kymmene", country: "Finland", industry: "Forestry/Materials", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €14.08B" },
  { name: "Covestro", country: "Germany", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €13.45B" },
  { name: "Jacobs Engineering", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €13.41B" },
  { name: "Metso", country: "Finland", industry: "Process Equipment Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €13.08B" },
  { name: "Yara International", country: "Norway", industry: "Chemicals (Fertilizers)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €13.06B" },
  { name: "Sartorius", country: "Germany", industry: "Bioprocess Equipment Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.95B" },
  { name: "Endeavour Mining", country: "United Kingdom", industry: "Mining (Gold)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.81B" },
  { name: "DT Midstream", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.68B" },
  { name: "Nordex", country: "Germany", industry: "Energy (Wind Engineering)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.51B" },
  { name: "Bureau Veritas", country: "France", industry: "Testing/Inspection Services", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.40B" },
  { name: "Sunoco", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.38B" },
  { name: "Albemarle", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €12.26B" },
  { name: "RPM International", country: "United States", industry: "Paint and Coatings", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.99B | Revenue 2024: €7.06B | Earnings 2024: €0.81B" },
  { name: "Var Energi", country: "Norway", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.83B" },
  { name: "Kerry Group", country: "Ireland", industry: "Food Ingredients", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.81B" },
  { name: "LG Chem", country: "South Korea", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.68B" },
  { name: "Eurofins Scientific", country: "Luxembourg", industry: "Lab Testing/Analytics", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.45B" },
  { name: "Italgas", country: "Italy", industry: "Gas Infrastructure Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.36B" },
  { name: "Symrise", country: "Germany", industry: "Specialty Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.19B" },
  { name: "Edison", country: "Italy", industry: "Utilities (Energy)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.18B" },
  { name: "Dycom Industries", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.13B" },
  { name: "APA Corporation", country: "United States", industry: "Oil and Gas", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.08B" },
  { name: "Recordati", country: "Italy", industry: "Pharma", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €11.05B" },
  { name: "Pentair", country: "United Kingdom", industry: "Industrial (Water Treatment Equipment)", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.82B" },
  { name: "GEA Group", country: "Germany", industry: "Process Equipment Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.44B" },
  { name: "SKF", country: "Sweden", industry: "Industrial (Bearings) Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.37B" },
  { name: "Romgaz", country: "Romania", industry: "Energy", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.33B" },
  { name: "Intertek", country: "United Kingdom", industry: "Testing/Inspection Services", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.27B" },
  { name: "Orion Corporation", country: "Finland", industry: "Pharma", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €10.20B" },
  { name: "AkzoNobel", country: "Netherlands", industry: "Chemicals", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4386912644&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €10B" },
  { name: "Smiths Group", country: "United Kingdom", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €9.31B" },
  { name: "Toray Industries", country: "Japan", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €9.15B" },
  { name: "Mitsubishi Chemical Holdings", country: "Japan", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €8.72B" },
  { name: "Westlake Corporation", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €8.65B | Revenue 2024: €11.67B | Earnings 2024: €0.82B" },
  { name: "Evonik Industries", country: "Germany", industry: "Chemicals", companySize: "", careersPageUrl: "https://www.evonik.com/en/careers/global-work-culture/north-america/students-graduates-north-america/evonik-rotation-program.html", researchNotes: "Market Cap: €7.88B" },
  { name: "AECOM", country: "United States", industry: "Engineering", companySize: "", careersPageUrl: "https://aecom.jobs/milan-ita/graduate-environmental-engineer/A86E61377B994FB191742A14D96EEA44/job/?vs=8010", researchNotes: "Market Cap: €7.65B | Revenue 2024: €15.59B | Earnings 2024: €0.86B" },
  { name: "ThyssenKrupp", country: "Germany", industry: "Engineering", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €7.59B" },
  { name: "Syensqo", country: "Belgium", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €7.19B" },
  { name: "Eastman Chemical", country: "United States", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €7.03B | Revenue 2024: €9.02B" },
  { name: "Axalta", country: "United States", industry: "Paint and Coatings", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €6.25B | Revenue 2024: €5.07B | Earnings 2024: €0.43B" },
  { name: "Arkema", country: "France", industry: "Chemicals", companySize: "", careersPageUrl: "", researchNotes: "Market Cap: €4.20B" },
  { name: "Solvay", country: "Belgium", industry: "Chemicals", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4436889364&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €2.75B\n\nOther open roles:\n- https://www.solvay.com/en/career/job-opportunities/33283?jobPipeline=Indeed" },
  { name: "Borealis", country: "Austria", industry: "", companySize: "6,000", careersPageUrl: "", researchNotes: "" },
  { name: "Topsoe", country: "Denmark", industry: "", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Stellantis", country: "Netherlands", industry: "Manufacturing", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Bosch", country: "Germany", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/bosch/manufacturing-engineering-graduate-specialist-program-2026?search_id=b7092eed347bcee1116947b1aac9d05e&search_position=9", researchNotes: "Other open roles:\n- https://www.joinrs.com/en/jobs/3259485" },
  { name: "Phoenix Pharmahandel", country: "Germany", industry: "", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Ineos", country: "United Kingdom", industry: "Petrochemical", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Chevron Phillips", country: "United States", industry: "Petrochemical", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Total Petrochemicals Gonfreville Complex", country: "France", industry: "Petrochemical", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Infineum", country: "United Kingdom", industry: "Petrochemical", companySize: "", careersPageUrl: "", researchNotes: "" },
  { name: "Fever", country: "Spain", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4400410527&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Munich Re", country: "Germany", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4431763497&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "EPS Group", country: "Ireland", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4440228133&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true", researchNotes: "" },
  { name: "Johnson & Johnson", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4443398643&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Technimont", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4438098001&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true&start=25", researchNotes: "" },
  { name: "Teladoc Health", country: "Spain", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4440224742&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true&start=25", researchNotes: "" },
  { name: "Procter & Gamble", country: "Germany", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4431521146&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Hexcel Corporation", country: "Spain", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4437066739&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true&start=50", researchNotes: "Other open roles:\n- https://www.linkedin.com/jobs/search/?currentJobId=4437076433&geoId=91000000&keywords=graduate%20engineer%20development%" },
  { name: "HP", country: "Spain", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4426563121&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Cargill", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4431991407&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Coesia", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4411869769&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true&start=75", researchNotes: "" },
  { name: "Flowserve Corporation", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4429110036&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Market Cap: €8.76B" },
  { name: "Nexi Italy", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4392584479&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Other open roles:\n- https://www.joinrs.com/en/jobs/3055695" },
  { name: "Goldbeck", country: "Germany", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4435545371&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Sumitomo Heavy Industries", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4443507095&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "TMC", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4434048165&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Vanderlande", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4435659582&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Accenture", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4427721734&geoId=91000000&keywords=graduate%20engineer%20development%20program&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&originalSubdomain=it&refresh=true&start=150", researchNotes: "" },
  { name: "Applied Materials Europe", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4436687254&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Other open roles:\n- https://appliedmaterialscareers.dejobs.org/milan-ita/field-service-engineer-new-college-graduate-program/8248CF3E56C641CF80C91498DCC852C1/job/?vs=8010" },
  { name: "Exyte", country: "Germany", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4434335330&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "Other open roles:\n- https://www.ziprecruiter.ie/jobs/558538950-engineering-graduate-2026-at-exyte-gmbh\n- https://www.ziprecruiter.ie/jobs/561034850-engineering-graduate-2026-at-exyte-gmbh\n- https://ch.indeed.com/viewjob?jk=24296fafbf21ed0b&from=shareddesktop_copy\n- https://ch.indeed.com/viewjob?jk=d96a12c33f57cdd5&from=shareddesktop_copy\n- https://ch.indeed.com/viewjob?jk=d1992cb0703c6b55&from=shareddesktop_copy" },
  { name: "Wood", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4383357527&geoId=91000000&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Avnet", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4402036454&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Canon", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4440590203&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Trinseo", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4412669648&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Lam Research", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4392154274&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Avertim", country: "Netherlands", industry: "", companySize: "", careersPageUrl: "https://www.linkedin.com/jobs/search/?currentJobId=4439157261&geoId=102890719&keywords=graduate%20engineer%20development%", researchNotes: "" },
  { name: "Volvo Group", country: "Sweden", industry: "", companySize: "", careersPageUrl: "https://www.volvogroup.com/en/careers/students-and-graduates/engineering-graduate-program.html", researchNotes: "" },
  { name: "Suir Engineering", country: "Denmark", industry: "", companySize: "", careersPageUrl: "https://dk.indeed.com/viewjob?jk=21a47d0624f73681&from=shareddesktop_copy", researchNotes: "" },
  { name: "Viatris", country: "Ireland", industry: "", companySize: "", careersPageUrl: "https://www.ziprecruiter.ie/jobs/557724306-graduate-rotation-programme-2026-supply-chain-at-viatris", researchNotes: "" },
  { name: "Johnson Controls", country: "Ireland", industry: "", companySize: "", careersPageUrl: "https://www.ziprecruiter.ie/jobs/552585559-engineering-graduate-at-johnson-controls", researchNotes: "" },
  { name: "Pell Frischmann", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/pell-frischmann/graduate-process-engineer-exeter-2026?search_id=ad35f3dcce430460d1573fd41dfcfade&search_position=10", researchNotes: "" },
  { name: "Ferrovial", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/ferrovial/graduate-quality-engineer-aylesbury-2026-aisl?search_id=1bace015799bce9bc3898d3dda590b3c&search_position=10", researchNotes: "" },
  { name: "Mcdermott", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/mcdermott/associate-piping-engineer-london-2026-ai98?search_id=8002ce41eddef7f3829b86de50f59b35&search_position=4", researchNotes: "" },
  { name: "Spectrum Control", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/api-microelectronics/junior-manufacturing-engineer-great-yarmouth-2026-aip2?search_id=66bac72089eecbd8a0c512f305119a04&search_position=2", researchNotes: "" },
  { name: "Heathcoat Fabrics", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/heathcoat-fabrics/graduate-development-programme-tiverton-2026-ahsm?search_id=af2fa7e65102b04b74c70b398e55d649&search_position=3", researchNotes: "" },
  { name: "Sibelco", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/sibelco/graduate-reliability-engineer-programme-newhouse-2026-ahzu?search_id=af2fa7e65102b04b74c70b398e55d649&search_position=6", researchNotes: "" },
  { name: "M&S, Gist", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/gist/fleet-engineering-graduate-basingstoke-2026-ahmv?search_id=af2fa7e65102b04b74c70b398e55d649&search_position=10", researchNotes: "" },
  { name: "Apollo", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/apollo/graduate-engineer-mechanical-structural-process-or-electrical-aberdeen-2026-ah8r?search_id=fa0db57a176b8013bd3c63bbf463c0fb&search_position=7", researchNotes: "" },
  { name: "Addison", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/addison/process-engineer-daresbury-2026?search_id=cb9ad832aebd68d893d69c42682601b1&search_position=3", researchNotes: "" },
  { name: "Framatome", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/framatome/process-engineer-cranfield-2026-aihr?search_id=57f4594eb29f373f2fbb1c86f0d84a1d&search_position=1", researchNotes: "" },
  { name: "Plessey Semiconductors", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.brightnetwork.co.uk/graduate-jobs/plessey-semiconductors-ltd/graduate-engineer-plymouth-2026-aiej?search_id=57f4594eb29f373f2fbb1c86f0d84a1d&search_position=2", researchNotes: "" },
  { name: "Johnson Matthey", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://matthey.wd3.myworkdayjobs.com/en-US/Ext_Career_Site/details/Join-Johnson-Matthey-Royston-_R-014740?jobFamilyGroup=697106e17ce70100b188220a0bfc0000&jobFamilyGroup=", researchNotes: "Other open roles:\n- https://matthey.wd3.myworkdayjobs.com/en-US/Ext_Career_Site/details/Hydrogen-Technologies-Test-Engineer_R-014977-1?jobFamilyGroup=697106e17ce70100b188220a0bfc0000&jobFamilyGroup=" },
  { name: "Ecolab", country: "United States", industry: "", companySize: "", careersPageUrl: "https://jobs.ecolab.com/global/en/job/R00292324/Junior-Process-Engineer", researchNotes: "Market Cap: €74B\n\nOther open roles:\n- https://jobs.ecolab.com/global/en/job/R00298693/Operation-Maintenance-Technician-UPW-Plant\n- https://ch.indeed.com/viewjob?jk=3c26793f3341af26&from=shareddesktop_copy" },
  { name: "Medtronic", country: "Ireland", industry: "", companySize: "", careersPageUrl: "https://ch.indeed.com/viewjob?jk=3847855adcde4da3&from=shareddesktop_copy", researchNotes: "Market Cap: €105B" },
  { name: "Abbott", country: "United States", industry: "", companySize: "", careersPageUrl: "https://www.jobs.abbott/us/en/job/31136422/Operations-Professional-Development-Program-PDP-Graduate-Programme", researchNotes: "Market Cap: €175B\n\nOther open roles:\n- https://www.jobs.abbott/us/en/job/31155780/Internship-Engineering\n- https://www.jobs.abbott/us/en/job/31154619/Manufacturing-Engineer-Line-Support\n- https://www.jobs.abbott/us/en/job/31146592/Operations-Support-Technician\n- https://www.jobs.abbott/us/en/job/31155397/Operations-Scientist-I\n- https://www.jobs.abbott/us/en/job/31154030/Process-Engineer" },
  { name: "Texas Instruments", country: "United States", industry: "", companySize: "", careersPageUrl: "https://careers.ti.com/en/sites/CX/job/25016648/?lastSelectedFacet=AttributeChar8&mode=location&selectedCategoriesFacet=300000068853972%253B300000068854028&selectedFlexFieldsFacets=%2522AttributeChar8%257CRecent+College+Grads%253BInterns%2522&selectedWorkLocationsFacet=300000069115418%253B300000068944151%253B300000068944283%253B300000068944478", researchNotes: "Market Cap: €260B" },
  { name: "Caterpillar", country: "United States", industry: "", companySize: "", careersPageUrl: "https://careers.caterpillar.com/en/jobs/r0000384564/manufacturing-engineer-technician-1-x-permanent-1-x-12m-contract/", researchNotes: "Market Cap: €412B\n\nOther open roles:\n- https://careers.caterpillar.com/en/jobs/r0000382627/manufacturing-engineer/\n- https://careers.caterpillar.com/en/jobs/r0000383869/prozess-wertstromverantwortlicher-manufacturing-engineering-mwd/\n- https://careers.caterpillar.com/en/jobs/r0000380896/manufacturing-engineer/" },
  { name: "Centrica", country: "United Kingdom", industry: "", companySize: "", careersPageUrl: "https://www.lifeatcentrica.com/jobs/r0080920/metering-apprentice/", researchNotes: "Market Cap: €9B\n\nOther open roles:\n- https://www.lifeatcentrica.com/jobs/r0078895/apprentice-gas-service-repair-engineer/" },
  { name: "Becton Dickinson", country: "United States", industry: "", companySize: "", careersPageUrl: "https://jobs.bd.com/en/job/enniscorthy/facilities-technician-12-month-ftc/159/98218155232", researchNotes: "Market Cap: €42B\n\nOther open roles:\n- https://jobs.bd.com/en/job/enniscorthy/r-and-d-engineer-i-product-engineering/159/98053474496" },
  { name: "Veeva", country: "United States", industry: "", companySize: "", careersPageUrl: "https://careers.veeva.com/job/d07a89ac-a962-47ee-abb2-78ffe7aa5f4c/associate-consultant-germany-entry-level-technology-consulting-life-sciences-frankfurt-germany/?lever-source=veeva-career-site", researchNotes: "Market Cap: €30B" },
  { name: "Stanley Black & Decker", country: "United States", industry: "", companySize: "", careersPageUrl: "https://sbdinc.wd1.myworkdayjobs.com/en-US/Stanley_Black_Decker_Career_Site/details/Operations-Manager_REQ-1000048713?jobFamilyGroup=138cf99b9c4910007a02e401ed540002&jobFamilyGroup=138cf99b9c4910007a02e0fb3b3f0000&locationCountry=29247e57dbaf46fb855b224e03170bc7&locationCountry=131d5ac7e3ee4d7b962bdc96e498e412&locationCountry=8cd04a563fd94da7b06857a79faaf815&locationCountry=dcc5b7608d8644b3a93716604e78e995&locationCountry=54c5b6971ffb4bf0b116fe7651ec789a&locationCountry=fc078443155c4ad294201ecf5a61a499", researchNotes: "Market Cap: €14B" },
  { name: "Adecco", country: "Switzerland", industry: "", companySize: "", careersPageUrl: "https://www.joinrs.com/en/jobs/3634544", researchNotes: "Market Cap: €4.60B" },
  { name: "Mondelez", country: "United States", industry: "", companySize: "", careersPageUrl: "https://mdlz.dejobs.org/capriata-d-orba-ita/taste-the-future-engineering-operations-leadership-graduate-program-capriata-dorba-italy-september-2026/A8FF931DD0C84266AEEDAAEED14AFFC5/job/", researchNotes: "Market Cap: €77B\n\nOther open roles:\n- https://www.joinrs.com/en/jobs/2875961" },
  { name: "Hilti", country: "Italy", industry: "", companySize: "", careersPageUrl: "https://www.joinrs.com/en/jobs/3806608", researchNotes: "Other open roles:\n- https://www.joinrs.com/en/jobs/3806632" },
  { name: "EssilorLuxottica", country: "France", industry: "", companySize: "", careersPageUrl: "https://www.joinrs.com/en/jobs/3486718", researchNotes: "Market Cap: €85B" },
  { name: "Thermo Fisher Scientific", country: "United States", industry: "", companySize: "", careersPageUrl: "https://thermofisher.dejobs.org/ferentino-ita/red-program-2026-scientific-track/BA4FBB859FB24C0C9A1B27A680EC3C24/job/?vs=8010", researchNotes: "Market Cap: €207B" },
  { name: "Abbvie", country: "United States", industry: "", companySize: "", careersPageUrl: "https://it.whatjobs.com/engineering-graduate-rotational-program-jobs/page-22?id=220339284", researchNotes: "Market Cap: €456B" },
];

export const DEFAULT_COMPANY_ENTRIES: ReadonlyArray<CompanyEntry> = COMPANY_SEED_DATA.map((seed, index) => ({
  ...createCompanyEntry(seed.name),
  id: `company-seed-${index + 1}`,
  country: seed.country,
  industry: seed.industry,
  companySize: seed.companySize,
  careersPageUrl: seed.careersPageUrl,
  notes: seed.researchNotes,
}));
