import { feature } from "topojson-client";
import { geoCentroid } from "d3-geo";
import type { Feature, FeatureCollection, Geometry } from "geojson";
import type { Topology } from "topojson-specification";
import worldTopology from "world-atlas/countries-110m.json";
import isoNumericData from "./data/country-iso-numeric.json";
import microstateFallbackData from "./data/microstate-fallback-coords.json";
import { WORLD_COUNTRIES, getCountriesForContinent } from "./countries";

export type CountryFeatureProperties = Readonly<{ name: string }>;

// Real country boundaries (Natural Earth, via world-atlas), converted once
// from topojson to GeoJSON at module load - the only place geographic data
// touches this app. Never edit country shapes by hand; everything renders
// straight from this. ~108KB, 177 features at 110m resolution.
export const WORLD_COUNTRY_FEATURES: FeatureCollection<Geometry, CountryFeatureProperties> = feature(
  worldTopology as unknown as Topology,
  (worldTopology as unknown as Topology).objects.countries as never,
) as unknown as FeatureCollection<Geometry, CountryFeatureProperties>;

// Generated by scripts/convert-world-map-excel.mjs's ISO-matching pass
// (name-matched against the real world-atlas feature list, not hand-typed) -
// maps 166 of the 195 seeded countries to their real ISO-3166-1 numeric code.
// The other 29 (Vatican, Monaco, San Marino, Singapore, Malta, and other
// small/island nations) have no individually renderable polygon at this
// resolution - see MICROSTATE_FALLBACK_COORDS below for those.
export const WORLD_COUNTRY_ISO_NUMERIC: Readonly<Record<string, number>> = isoNumericData;

// Real capital-city lon/lat for the 29 countries without a world-atlas
// polygon - hand-authored (a far smaller, tractable list than all 195),
// so those countries still render a clickable, real-position marker even
// without a filled territory shape.
const MICROSTATE_FALLBACK_COORDS = microstateFallbackData as unknown as Readonly<Record<string, readonly [number, number]>>;

const FEATURE_BY_ISO_NUMERIC = new Map(WORLD_COUNTRY_FEATURES.features.map((featureItem) => [Number(featureItem.id), featureItem]));

export function getCountryFeature(countryId: string) {
  const isoNumeric = WORLD_COUNTRY_ISO_NUMERIC[countryId];
  return isoNumeric !== undefined ? (FEATURE_BY_ISO_NUMERIC.get(isoNumeric) ?? null) : null;
}

// The projection is fit to the actual shapes being shown, not a synthetic
// bounding box - a hand-authored lon/lat rectangle risks the wrong GeoJSON
// ring winding (interpreted by d3-geo as "the rest of the sphere"). Fitting
// to real feature geometry sidesteps that and is more true to "real data".

// Every real country except Antarctica (whose true shape stretches to -90
// latitude and would otherwise dominate the fit) - the frame the World view
// zooms to.
export const WORLD_FRAME: FeatureCollection<Geometry, CountryFeatureProperties> = {
  type: "FeatureCollection",
  features: WORLD_COUNTRY_FEATURES.features.filter((featureItem) => featureItem.properties.name !== "Antarctica"),
};

// A continent's frame = the real shapes of its own seeded countries, so
// zooming in fits tightly around exactly what's interactive there. Falls
// back to the continent's bounding box (below) when none of its countries
// have a real polygon (shouldn't happen at continent scale, but safe).
export function getContinentFrame(continentId: string): FeatureCollection<Geometry, CountryFeatureProperties> | null {
  const features = getCountriesForContinent(continentId)
    .map((country) => getCountryFeature(country.id))
    .filter((featureItem): featureItem is Feature<Geometry, CountryFeatureProperties> => featureItem !== null);

  return features.length > 0 ? { type: "FeatureCollection", features } : null;
}

// Real (approximate) lon/lat bounding boxes per continent - used only to
// place each continent's label marker in the World view, not for fitting the
// projection (see getContinentFrame above).
const CONTINENT_BOUNDS: Readonly<Record<string, Readonly<{ lon0: number; lat0: number; lon1: number; lat1: number }>>> = {
  europe: { lon0: -25, lat0: 34, lon1: 45, lat1: 71 },
  "north-america": { lon0: -170, lat0: 5, lon1: -50, lat1: 75 },
  africa: { lon0: -20, lat0: -35, lon1: 55, lat1: 38 },
  asia: { lon0: 26, lat0: -10, lon1: 150, lat1: 55 },
  "south-america": { lon0: -82, lat0: -56, lon1: -34, lat1: 13 },
  oceania: { lon0: 110, lat0: -48, lon1: 180, lat1: 5 },
};

export function getContinentCentroid(continentId: string): readonly [number, number] | null {
  const bounds = CONTINENT_BOUNDS[continentId];
  return bounds ? [(bounds.lon0 + bounds.lon1) / 2, (bounds.lat0 + bounds.lat1) / 2] : null;
}

// Marker coordinates for every one of the 195 countries: the real
// geographic centroid for the 166 with a world-atlas polygon (computed once,
// never hand-typed), and the authored fallback for the other 29. Built once
// at module load.
const COUNTRY_MARKER_COORDS: ReadonlyMap<string, readonly [number, number]> = (() => {
  const map = new Map<string, readonly [number, number]>();

  WORLD_COUNTRIES.forEach((country) => {
    const featureItem = getCountryFeature(country.id);

    if (featureItem) {
      const [lon, lat] = geoCentroid(featureItem);
      if (Number.isFinite(lon) && Number.isFinite(lat)) {
        map.set(country.id, [lon, lat]);
        return;
      }
    }

    const fallback = MICROSTATE_FALLBACK_COORDS[country.id];
    if (fallback) {
      map.set(country.id, fallback);
    }
  });

  return map;
})();

export function getCountryMarkerCoords(countryId: string): readonly [number, number] | null {
  return COUNTRY_MARKER_COORDS.get(countryId) ?? null;
}

function haversineDistanceKm(a: readonly [number, number], b: readonly [number, number]): number {
  const toRadians = (degrees: number) => (degrees * Math.PI) / 180;
  const [lon1, lat1] = a;
  const [lon2, lat2] = b;
  const earthRadiusKm = 6371;
  const dLat = toRadians(lat2 - lat1);
  const dLon = toRadians(lon2 - lon1);
  const haversine = Math.sin(dLat / 2) ** 2 + Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * earthRadiusKm * Math.asin(Math.sqrt(haversine));
}

export type NearestCountry = Readonly<{ id: string; distanceKm: number }>;

// Real geographic distance between countries, using the same marker
// coordinates the map renders from - no adjacency/border dataset needed.
// Drives Rival movement (world-map/rival-simulation-engine.ts) so a rival
// steps to nearby countries instead of teleporting across the globe.
export function getNearestCountries(countryId: string, limit = 25): ReadonlyArray<NearestCountry> {
  const origin = COUNTRY_MARKER_COORDS.get(countryId);

  if (!origin) {
    return [];
  }

  return Array.from(COUNTRY_MARKER_COORDS.entries())
    .filter(([id]) => id !== countryId)
    .map(([id, coords]) => ({ id, distanceKm: haversineDistanceKm(origin, coords) }))
    .sort((a, b) => a.distanceKm - b.distanceKm)
    .slice(0, limit);
}

// Deterministic per-city layout within a country's zoomed view - real
// per-city coordinates don't exist in the source data (see WorldCity.
// coordinates), so a country's cities are arranged in a small fixed
// triangular offset pattern around the country's own real marker position,
// keyed by the city's index so it's stable and reproducible, not invented
// precision. Offsets are in degrees, scaled down for small countries by the
// caller if needed.
const CITY_LAYOUT_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [0, 0.6],
  [-0.55, -0.35],
  [0.55, -0.35],
];

export function getCityLayoutCoords(countryId: string, cityIndex: number): readonly [number, number] | null {
  const origin = getCountryMarkerCoords(countryId);
  if (!origin) {
    return null;
  }

  const offset = CITY_LAYOUT_OFFSETS[cityIndex % CITY_LAYOUT_OFFSETS.length];
  return [origin[0] + offset[0], origin[1] + offset[1]];
}
